### PR TITLE
Update Python versions

### PR DESCRIPTION
**Pull request by edmorley**
I bumped all Python versions to the latest patch release.

In addition, I changed garnet's Python 3 version from 3.5.x to 3.6.x, since if it is only going to install one of each of Python 2 and 3, then it makes sense for it to be the latest of each. I'm happy to revert this part if preferred.

For latest version numbers see:
https://www.python.org/downloads/

### CODE REVIEW

**Comment by Lyoness** [comment]
@edmorley - repeating what I did for the php updates by merging this into my own branch to trigger packer-builds. 

https://github.com/travis-ci/packer-templates/tree/cha-edmorley-python-update

**Comment by Lyoness** [comment]
[Sugilite is failing here](https://travis-ci.org/travis-infrastructure/packer-build/builds/268349320#L1417) :no_entry_sign:

**Comment by Lyoness** [comment]
Garnet [failing on the specs](https://travis-ci.org/travis-infrastructure/packer-build/jobs/268349305#L5550) :no_entry_sign:

**Comment by edmorley** [comment]
Now that I've figured out the `dev: true` annotation, I have a specs fix locally - however I'll wait to update/test this until the sugilite removal and other PRs have landed for simplicity/to reduce conflicts.

**Comment by meatballhat** [comment]
@edmorley Ack!  I've introduced conflicts with the removal of sugilite.  Sorrryyyy

**Comment by edmorley** [comment]
I'm going to move this to a branch on this repo rather than my fork, since then it's easier to trigger the test builds.

**Pull request closed without merging**
