### PR TITLE
Ensure rich trusty stacks have GLX extension

### LINKED ISSUE #220: Xlib extension GLX missing
https://travis-ci.org/OGRECave/ogre/jobs/151073923#L4156
https://travis-ci.org/starviewer-medical/starviewer/jobs/150746360
https://travis-ci.org/d-meiser/qtopengl/builds/151384137

### PR DESCRIPTION
**Pull request by meatballhat**
Closes #220

### CODE REVIEW

**Comment by meatballhat** [comment]
This is not going well.  I'm not able to coax the GLX out of anything.  Requires more research.

**Comment by meatballhat** [comment]
I'm finding that purging `fglrx` will result in the `GLX` and `SGI-GLX` extensions reappearing:

``` bash
~$ xvfb-run xdpyinfo | grep -c GLX
0
~$ sudo apt purge -y fglrx
Reading package lists... Done
Building dependency tree
Reading state information... Done
# ... etc
~$ xvfb-run xdpyinfo | grep -c GLX
2
```

**Comment by paroj** [comment]
so when is this this change expected to land? or do I have to specify `group: xxx` or something?

**Comment by solarce** [comment]
This has not been put into production, you can test it by adding `group: edge` to your `.travis.yml`, we hope to have promote it to the stable image on Monday.

**Pull request merged**
