### PR TITLE
Stub in xenial stack successors

### PR DESCRIPTION
**Pull request by meatballhat**
as:

- amethyst :arrow_right: [opal](http://steven-universe.wikia.com/wiki/Opal)
- garnet :arrow_right: [sardonyx](http://steven-universe.wikia.com/wiki/Sardonyx)

### What is the problem that this PR is trying to fix?

There is a project in the works that needs to begin playing with xenial-specific stacks that correspond with amethyst and garnet.

### What approach did you choose and why?

I copied `ci-stevonnie.yml` to `ci-opal.yml` and `ci-sardonyx.yml` and then copied `travis_ci_{garnet,sardonyx}` and `travis_ci_{amethyst,opal}`, and then copied the packages asset files similarly, all as a starting point, all without expectations that it will work _at all_.  I expect that within the scope of this PR, I will continue to add changes until the stacks are creating images, even if that means everything is commented out...

### How can you test this?

Pushing the packer-builds through the pipe!

### What feedback would you like?

Are `opal` and `sardonyx` reasonable choices?  My thinking was that these are the slightly more advanced/powerful fusions with Pearl, who is (tragically!) not represented in the Trusty generation of templates.

### CODE REVIEW

**Comment by Lyoness** [comment]
cry_for_help_sardonyx_02
:heart:

**Comment by Lyoness** [comment]
opal
:heart_decoration:

**Comment by edmorley** [comment]
I think this PR raced with #491, so `cookbooks/travis_ci_sardonyx/attributes/default.rb` is missing those changes to `cookbooks/travis_ci_garnet/attributes/default.rb`:
https://github.com/travis-ci/packer-templates/pull/491/files#diff-28e4e697120326dd443e6c942510e346

**Comment by edmorley** [comment]
> I think this PR raced with #491, so cookbooks/travis_ci_sardonyx/attributes/default.rb is missing those changes to cookbooks/travis_ci_garnet/attributes/default.rb

Resolved in #548.

**Pull request merged**
