### PR TITLE
Add IBM Java 8 as a java alternative to garnet

### PR DESCRIPTION
**Pull request by bogdanap**
## What is the problem that this PR is trying to fix?
Fixes https://github.com/travis-pro/team-blue/issues/703

## What approach did you choose and why?
Add the new recipe as an alternative.

## How can you test this?
Image built and tested as part of https://github.com/travis-ci/travis-cookbooks/pull/874

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
Woot! Will this be available immediately? Should I wait an hour for it to roll out?

**Comment by bogdanap** [comment]
@JLLeitschuh It will be available as soon as the new image is built (assuming it succeeds): https://travis-ci.org/travis-infrastructure/packer-build/jobs/285670975 😄

**Comment by JLLeitschuh** [comment]
So, no good because the build failed?

**Comment by bogdanap** [comment]
@JLLeitschuh Unfortunately not - there GPG for the mongo repo is expired (https://jira.mongodb.org/browse/SERVER-31459) and it's currently blocking any new image builds. 
I can ping you once this is solved and the new image is ready to go.

**Comment by JLLeitschuh** [comment]
Thank you so much!

**Comment by chandrams** [comment]
@JLLeitschuh, I tried using the IBM Java8 in the matrix, it works for me. You can give it a try.
https://travis-ci.org/chandrams/myproj/builds/286945151

**Comment by chandrams** [comment]
@bogdanap - Is IBM Java8 part of Trusty stable image update now? I 'm able to use it via the matrix but not using jdk_switcher yet. By when will it be included? Thanks.

**Comment by bogdanap** [comment]
@chandrams We haven't made any updates to stable yet, so for now it's only available in edge. It will be officially announced as part of our Trusty Q4 update which is expected early December.

**Comment by bogdanap** [comment]
@chandrams We use the `group: edge` tag for images built from the master branch of both `packer-templates` and `travis-cookbooks` (so these change with every merge to master).

We use `group: stable` as the default images that users get when running builds with Travis, which change less often and are usually announced publicly: https://docs.travis-ci.com/user/build-environment-updates/. When this happens, usually the latest `edge` build gets promoted to `stable`.

**Comment by chandrams** [comment]
Thanks for the explanation @bogdanap

**Comment by chandrams** [comment]
@bogdanap - You had mentioned IBM Java8 will be made available in the official trusty image early december, any outlook dates?

**Comment by bogdanap** [comment]
Hi @chandrams. I'm afraid I have bad news 😢  - after the recent issues with the key mismatch, we've had a more in-depth chat about the contents of the Q4 updates. 

Since this will serve as our LTS image (as announced in [the latest blog post](https://blog.travis-ci.com/2017-12-01-new-update-schedule-for-linux-build-images)) we've decided to keep the changes minimal and not add any new features.

This means that we'll be looking at introducing the IBM Java 8 support with Xenial early next year and possibly on the `travis_latest` track for Trusty,

**Comment by chandrams** [comment]
@bogdanap - Any updates?

**Comment by bogdanap** [comment]
Hi @chandrams. Unfortunately, I have no updates yet.
Our current focus lies outside the build environment, so I doubt we will make any update in the next month or so. 
I would keep an eye out for the official Xenial Beta announcement and release for this.

**Comment by chandrams** [comment]
@bogdanap Any updates on this? This is pending for quite a while now. Thanks.

**Comment by bogdanap** [comment]
Unfortunately, my response is the same as [the previous one](https://github.com/travis-ci/packer-templates/pull/527#issuecomment-359389275). We have limited resources and are currently focused on other priorities. 😢

**Pull request merged**
