### PR TITLE
Try out bumped docker + docker-compose versions

### PR DESCRIPTION
**Pull request by meatballhat**

### CODE REVIEW

**Comment by Lyoness** [comment]
Pairs with: https://github.com/travis-ci/travis-cookbooks/pull/770 for 

>>>explicitly installing and upgrading the backported xenial kernel in order to
(hopefully) get the latest patches related to unregister_netdevice

 next steps?  Start an image from `ami-fafafafaf` to run builds, or does this get promoted through tags for job-board-staging?

**Comment by meatballhat** [comment]
@Lyoness PRs like this are a bit odd to me, which is why I label them with `wip`, as I'm opening the PR almost exclusively to trigger a packer build of some change made in travis-cookbooks.  I also tend to treat these on a case by case basis, as the impact of the potential changes can vary widely.  In *this* case, I feel like the impact is mostly positive and low risk, so I'd be in favor of merging it in to be part of the next wave of `group: edge` images, and eventually part of `group: stable`.

**Comment by meatballhat** [comment]
@Lyoness I should also mention that I don't intend this particular PR to be merged, as the only change is a hardcoded branch name that I'd have to back out anyway.

**Comment by meatballhat** [comment]
@Lyoness whoopsie, one more thing!

> Pairs with: travis-ci/travis-cookbooks#770 for

This is not true :grin:

Instead, it's associated with the already-merged https://github.com/travis-ci/travis-cookbooks/pull/768

**Comment by Lyoness** [comment]
womp. thanks for clarifying! :heart:

**Pull request closed without merging**
