### PR TITLE
Remove the Sugilite stack

### PR DESCRIPTION
**Pull request by meatballhat**
since the Amethyst and Garnet stacks are sufficient to cover
container-based needs, and the difference across container-based and
fully-virtualized adds confusion.

### CODE REVIEW

**Comment by bogdanap** [comment]
While I'm all for consistency between our infras, I wonder whether this will impact some users and how many of them. Do we have everything that was included in sugilite covered between garnet and amethyst?

**Comment by meatballhat** [comment]
@bogdanap "everything" is covered for most cases, imho.  The thing that sugilite offers that isn't present on either amethyst or garnet is the presence of both sets of features, meaning that sugilite itself is the unique feature.  We don't offer sugilite on container-based, which is where most of our jobs run, and I'm not aware of any users who are dependent on a sudo-enabled environment having a specific cross-section of features than only sugilite can provide, but I assume they exist.

**Comment by edmorley** [comment]
Yey for simplification and greater consistency across container and GCE!

**Comment by meatballhat** [comment]
We hardly knew ye

**Comment by bogdanap** [comment]
If my manual filtering is correct, these are the tags that are only covered by Sugilite:
```
language_hhvm: 'true'
language_mega: 'true'
language_perl6: 'true'
feature_sphinxsearch: 'true'
```
Assuming we want to drop support completely, we should also remove the corresponding cookbooks. Otherwise, it might be worth re-assigning them to garnet and/or amethyst.

I've left out 
```
language_legacy: 'true'
language_generic: 'true'
``` 
from the list above, because I wasn't sure how they affect things.

**Comment by meatballhat** [comment]
@bogdanap I think we can safely drop all of the language and feature tags you've listed 👍

**Comment by emdantrim** [comment]
@meatballhat even perl6? is there a separate just-`perl`?

**Comment by edmorley** [comment]
So one side-effect of `generic` no longer being specified as a language anywhere is that `group: edge, language: generic` results in an old sugilite image, rather than a new garnet/... image. Is this intended? Will the old tags be removed from job board when this goes to stable, so people don't get unknowningly left behind on older images? :-)

**Pull request merged**
