### PR TITLE
Add some help/usage/comment for check-job-board-tags

### PR DESCRIPTION
**Pull request by meatballhat**

### CODE REVIEW

**Comment by meatballhat** [comment]
@igorwwwwwwwwwwwwwwwwwwww r?

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
things that came up:

* what is a tagset? what's the difference between languages and features?
* what is an inclusive relationship?
* what is an exclusive relationship?
* why are those relationships in that way? what is the high-level idea behind these constraints?

**Comment by meatballhat** [comment]
@igorwwwwwwwwwwwwwwwwwwww I want to answer your questions somewhere that is more easily accessible than comments, but I don't feel like the usage/help of the script is the right place for that.  Would you be OK with me addressing these questions in the README?

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
@meatballhat yeah, README works for me :)

**Comment by meatballhat** [comment]
@igorwwwwwwwwwwwwwwwwwwww I'm feeling very tautological 😬   halp.

**Pull request merged**
