### PR TITLE
Merging #247

### PR DESCRIPTION
**Pull request by meatballhat**

### CODE REVIEW

**Comment by meatballhat** [comment]
@adelcambre This is the "downstream" build that ultimately determines if this patch can be merged: https://travis-ci.org/travis-infrastructure/packer-build/jobs/152531449

**Comment by adelcambre** [comment]
@meatballhat Interesting, it looks like it's failing for some unrelated reason. These are the two failing specs I see, looks like it's trying to expect on the `git config`.

```
    googlecompute: rspec /tmp/packer-chef-client/cookbooks-0/lib/features/git_spec.rb[1:3:1:1] # git installation Command "git config user.name" stdout should match /travis/i
    googlecompute: rspec /tmp/packer-chef-client/cookbooks-0/lib/features/git_spec.rb[1:4:1:1] # git installation Command "git config user.email" stdout should match /travis@example\.org/
```

**Comment by meatballhat** [comment]
@adelcambre Yep, I think I know what's going on here.  That spec was related to work I did for packer templates built on Ubuntu Trusty, with my intent being to backport the changes to Ubuntu Precise templates right away.  I'll get those specs tagged `precise: false` so that they're [ignored for now](https://github.com/travis-ci/packer-templates/blob/68c33e6753d719126c4f880fa8da3b2690a14e79/packer-scripts/run-serverspecs#L21-L23).

**Comment by meatballhat** [comment]
Looks good! :+1: :grin: https://travis-ci.org/travis-infrastructure/packer-build/jobs/152564049

**Pull request merged**
